In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 731c5ac602752760c8e48fbffcf8c3b850d9dc2a2aedcf2cc48468fc17b673d1 so we will re-download the data.
11493376/11490434 [==============================] - 890s 77us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.3334276 ,  0.101026  , -0.20545723, -0.04859342,  0.24713929,
         0.03759575,  0.11668709, -0.38101527, -0.05620632,  0.66943574]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.06750371, 0.10423377, 0.07671928, 0.08974899, 0.12063257,
        0.09782752, 0.10587903, 0.0643666 , 0.08906832, 0.18402027]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3245492

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2943 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1468 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1098 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0885 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0761 - accuracy: 0.9760


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0732 - accuracy: 0.9784


[0.07317836582660675, 0.9783999919891357]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.3371861e-08, 7.8395148e-09, 6.2859085e-06, 1.2016150e-04,
        8.3635647e-11, 4.6858180e-08, 5.3045616e-13, 9.9987066e-01,
        1.0776425e-08, 2.8523698e-06],
       [3.1305312e-08, 4.8976519e-05, 9.9988365e-01, 4.0296825e-05,
        2.0465862e-15, 1.7759652e-05, 5.6712361e-07, 5.4311646e-12,
        8.6613081e-06, 1.8039415e-14],
       [5.5125797e-09, 9.9935395e-01, 5.6269437e-05, 2.1214930e-06,
        1.1073929e-05, 2.7734554e-06, 6.9423963e-06, 5.0716416e-04,
        5.9687743e-05, 1.3027859e-07],
       [9.9998951e-01, 4.1118278e-10, 1.8724551e-06, 5.8321931e-10,
        5.9720435e-08, 1.5110241e-07, 7.3965984e-06, 8.7388304e-07,
        1.1291357e-09, 8.9701786e-08],
       [2.5996840e-06, 1.3874351e-09, 2.4361384e-06, 1.8614298e-07,
        9.9391514e-01, 2.7238150e-07, 2.0567702e-06, 6.3583961e-06,
        1.3752622e-06, 6.0695913e-03]], dtype=float32)>